BlogApp/Pages/Blog/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using DAL;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;

namespace BlogApp.Pages.Blog
{
    //[Authorize]
    public class CreateModel : PageModel
    {
        private readonly DataContext _context;

        public CreateModel(DataContext context)
        {
            _context = context;
        }

        [BindProperty]
        public DAL.Models.Blog blogs { get; set; }

        public void OnGet()
        { 

        }

        public IActionResult OnPost() 
        {
            if (ModelState.IsValid)
            {
                _context.Blogs.Add(blogs);
                _context.SaveChanges();
                return RedirectToPage("./Index");
            }
            else
            {
                return Page();
            }
        }

        //multiple page handler
        public IActionResult OnPostFinish(int id)
        {
            if(!ModelState.IsValid)
            {
                return RedirectToPage("./Index");
            }
            else
            {
                return Page();
            }
        }

    }
}

BlogApp/Pages/Blog/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DAL;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;

namespace BlogApp.Pages.Blog
{
    [Authorize]
    public class DeleteModel : PageModel
    {
        private readonly DataContext _context;

        public DeleteModel(DataContext context)
        {
            _context = context;
        }

        [BindProperty]
        public DAL.Models.Blog blogs { get; set; }

        public void OnGet(int id)
        {
            blogs = _context.Blogs.FirstOrDefault(b => b.BlogId == id);
        }

        public IActionResult OnPost()
        {
            _context.Blogs.Remove(blogs);
            _context.SaveChanges();
            return RedirectToPage("./Index");
        }
    }

}

        

BlogApp/Pages/Blog/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DAL;
using DAL.Models;

namespace BlogApp.Pages.Blog
{
    public class DetailsModel : PageModel
    {
        private readonly DAL.DataContext _context;

        public DetailsModel(DAL.DataContext context)
        {
            _context = context;
        }

    }
}

BlogApp/Pages/Blog/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;

namespace BlogApp.Pages.Blog
{
    [Authorize]
    public class EditModel : PageModel
    {
        private readonly DAL.DataContext _context;

        public EditModel(DAL.DataContext context)
        {
            _context = context;
        }

        [BindProperty]
        public DAL.Models.Blog blogs { get; set; }

        public void OnGet(int id)
        {
            blogs = _context.Blogs.FirstOrDefault(b => b.BlogId == id);
        }

        public IActionResult OnPost()
        {
            _context.Blogs.Update(blogs);
            _context.SaveChanges();
            return RedirectToPage("./Index");
        }
    }
}

BlogApp/Pages/Blog/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DAL;
using DAL.Models;

namespace BlogApp.Pages.Blog
{
    public class IndexModel : PageModel
    {
        private readonly DAL.DataContext _context;

        public IndexModel(DAL.DataContext context)
        {
            _context = context;
        }

        public List<DAL.Models.Blog> blogs { get; set; }

        public IActionResult Onget(string searchQuery)
        {
            //search operation
            if (!string.IsNullOrEmpty(searchQuery))
            {
                blogs = _context.Blogs.Where(b => b.Title.Contains(searchQuery)).ToList();
            }
            else
            {
                blogs = _context.Blogs.ToList();
            }
            return Page();
        }

    }
}

BlogApp/Pages/Post/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using DAL;
using DAL.Models;

namespace BlogApp.Pages.Post
{
    public class CreateModel : PageModel
    {
        private readonly DAL.DataContext _context;

        public CreateModel(DAL.DataContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        //ViewData["BlogId"] = new SelectList(_context.Blogs, "BlogId", "Url");
            return Page();
        }

        [BindProperty]
        public DAL.Models.Post Post { get; set; } = default!;

        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Posts.Add(Post);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

BlogApp/Pages/Post/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DAL;
using DAL.Models;

namespace BlogApp.Pages.Post
{
    public class DeleteModel : PageModel
    {
        private readonly DAL.DataContext _context;

        public DeleteModel(DAL.DataContext context)
        {
            _context = context;
        }

        [BindProperty]
        public DAL.Models.Post Post { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FirstOrDefaultAsync(m => m.PostId == id);

            if (post == null)
            {
                return NotFound();
            }
            else
            {
                Post = post;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FindAsync(id);
            if (post != null)
            {
                Post = post;
                _context.Posts.Remove(Post);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

BlogApp/Pages/Post/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DAL;
using DAL.Models;

namespace BlogApp.Pages.Post
{
    public class DetailsModel : PageModel
    {
        private readonly DAL.DataContext _context;

        public DetailsModel(DAL.DataContext context)
        {
            _context = context;
        }

        public DAL.Models.Post Post { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FirstOrDefaultAsync(m => m.PostId == id);
            if (post == null)
            {
                return NotFound();
            }
            else
            {
                Post = post;
            }
            return Page();
        }
    }
}

BlogApp/Pages/Post/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL;
using DAL.Models;

namespace BlogApp.Pages.Post
{
    public class EditModel : PageModel
    {
        private readonly DAL.DataContext _context;

        public EditModel(DAL.DataContext context)
        {
            _context = context;
        }

        [BindProperty]
        public DAL.Models.Post Post { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post =  await _context.Posts.FirstOrDefaultAsync(m => m.PostId == id);
            if (post == null)
            {
                return NotFound();
            }
            Post = post;
          // ViewData["BlogId"] = new SelectList(_context.Blogs, "BlogId", "Url");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Post).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PostExists(Post.PostId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool PostExists(int id)
        {
            return _context.Posts.Any(e => e.PostId == id);
        }
    }
}

BlogApp/Pages/Blog/Create.cshtml
@page
@model BlogApp.Pages.Blog.CreateModel

@{
    ViewData["Title"] = "Create";
}

<form  method="post">
    <div class="mb-3">
        <label asp-for="@Model.blogs.Title" class="form-label">Titlel</label>
        <input asp-for="@Model.blogs.Title" type="text" class="form-control" id="formGroupExampleInput" placeholder="Example input placeholder">
    </div>
    <div class="mb-3">
        <label asp-for="@Model.blogs.Description" class="form-label">Description</label>
        <textarea asp-for="@Model.blogs.Description"  type="text" class="form-control" id="formGroupExampleInput2" placeholder="Another input placeholder"><</textarea>
    </div>
    <div class="mb-3">
        <label asp-for="@Model.blogs.Rating" class="form-label">Rating</label>
        <input type="number" asp-for="@Model.blogs.Rating" class="form-control" id="formGroupExampleInput2" placeholder="Another input placeholder">
    </div>

    <button type="submit" class="btn btn-primary">Create</button>
</form>



@*multiple page handlers*@
<h2>Form 2</h2>
<form method="post" asp-page-handler="Finish">
    <input type="text" name="searchQuery"  class="form-control"  placeholder="search..." />
    <button type="submit" class="btn btn-primary">Finish</button>
</form>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BlogApp/Pages/Blog/Delete.cshtml
@page
@model BlogApp.Pages.Blog.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<form method="post">
    <div class="mb-3">
        <label asp-for="@Model.blogs.BlogId" class="form-label">BlodId</label>
        <input asp-for="@Model.blogs.BlogId" type="text" class="form-control" id="formGroupExampleInput" placeholder="Example input placeholder" hidden>
    </div>
    <div class="mb-3">
        <label asp-for="@Model.blogs.Title" class="form-label">Titlel</label>
        <input asp-for="@Model.blogs.Title" type="text" class="form-control" id="formGroupExampleInput" placeholder="Example input placeholder" disabled>
    </div>
    <div class="mb-3">
        <label asp-for="@Model.blogs.Description" class="form-label">Description</label>
        <textarea asp-for="@Model.blogs.Description" type="text" class="form-control" id="formGroupExampleInput2" placeholder="Another input placeholder" disabled><</textarea>
    </div>
    <div class="mb-3">
        <label asp-for="@Model.blogs.Rating" class="form-label">Rating</label>
        <input type="number" asp-for="@Model.blogs.Rating" class="form-control" id="formGroupExampleInput2" placeholder="Another input placeholder" disabled>
    </div>

    <button type="submit" class="btn btn-danger">Delete</button>
</form>

BlogApp/Pages/Blog/Details.cshtml
@page
@model BlogApp.Pages.Blog.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

BlogApp/Pages/Blog/Edit.cshtml
@page
@model BlogApp.Pages.Blog.EditModel

@{
    ViewData["Title"] = "Edit";
}

<form method="post">
    <div class="mb-3">
        <label asp-for="@Model.blogs.BlogId" class="form-label">BlodId</label>
        <input asp-for="@Model.blogs.BlogId" type="text" class="form-control" id="formGroupExampleInput" placeholder="Example input placeholder" hidden>
    </div>
    <div class="mb-3">
        <label asp-for="@Model.blogs.Title" class="form-label">Titlel</label>
        <input asp-for="@Model.blogs.Title" type="text" class="form-control" id="formGroupExampleInput" placeholder="Example input placeholder">
    </div>
    <div class="mb-3">
        <label asp-for="@Model.blogs.Description" class="form-label">Description</label>
        <textarea asp-for="@Model.blogs.Description" type="text" class="form-control" id="formGroupExampleInput2" placeholder="Another input placeholder"><</textarea>
    </div>
    <div class="mb-3">
        <label asp-for="@Model.blogs.Rating" class="form-label">Rating</label>
        <input type="number" asp-for="@Model.blogs.Rating" class="form-control" id="formGroupExampleInput2" placeholder="Another input placeholder">
    </div>

    <button type="submit" class="btn btn-warning">Edit</button>
</form>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BlogApp/Pages/Blog/Index.cshtml
@page
@model BlogApp.Pages.Blog.IndexModel

@{
    ViewData["Title"] = "Index";
}

<a asp-page="./Create" class="btn btn-primary">Create a Blog</a>

@*searching*@
<form method="get" class="input-group mb-3" id="search_form ">
    <input type="text" name="searchQuery" onkeyup="greet()" class="form-control" id="input_search" placeholder="search..." />
    <button class="btn btn-outline-secondary" type="submit" id="btn_search">Search</button>
</form>

@if(TempData["blog-create"]is not null)
{
    
}

    @{
        if(Model.blogs.Any())
        {
            
        }
        else
        {
            <h2>No blog found</h2>            
        }
    }




@foreach(var obj in Model.blogs){
<div class="card mt-4">
    <div class="card-header">
        @obj.Title
    </div>
    <div class="card-body">
        <h5 class="card-title">@obj.Rating</h5>
        <p class="card-text">@obj.Description</p>
        <a asp-page="Edit" asp-route-id="@obj.BlogId" class="btn btn-warning">Edit</a>
        <a asp-page="Delete" asp-route-id="@obj.BlogId" class="btn btn-danger">Delete</a>
    </div>
</div>
}


@section Scripts{
    <script>
        let search = document.getElementById("input_search")
        let btn = document.getElementById("btn_search")
        let form = document.getElementById("search_form")

       function greet(){
            if(search.value.length >= 3){
                //console.log("hello")
                btn.click()
            }
        }
    </script>
}